### ISSUE TITLE
Unable to update Bug Bounty files: "Command 'bbrecon get programs --type web -o json' returned non-zero exit status 1".

### ISSUE THREAD

**Issue by Stargate38** [Zarcolio/sitedorks#6]
Full error when running "sitedorks -ubb":

Traceback (most recent call last):
  File "/usr/local/bin/sitedorks", line 64, in <module>
    sOutput = subprocess.check_output("bbrecon get programs --type web -o json", shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bbrecon get programs --type web -o json' returned non-zero exit status 1.

Is there any way at all to update the Bug Bounty files? I tried to get an API key for bbrecon, but I get a connection timeout when I try to do so.

**Comment by Zarcolio** [comment]
I'm truly sorry for the late comment, but since bbrecon has been discontinued, I've removed support for it from SiteDorks.
Maybe in the future, if I have the time, I'll look for another possibility 😎
